"""Cross-problem knowledge: accepted results and relevance links between problems."""

from __future__ import annotations

import json
import threading
from typing import Any

from .integrity import IntegrityGuard
from .jsonio import read_jsonl, utc_now
from .paths import WorkspacePaths
from .state import TRUST_ORDER, Claim


class KnowledgeBase:
    def __init__(self, paths: WorkspacePaths, guard: IntegrityGuard) -> None:
        self.paths = paths
        self.guard = guard
        self._lock = threading.Lock()

    def _append(self, path, records: list[dict[str, Any]]) -> None:
        if not records:
            return
        existing = path.read_bytes() if path.is_file() else b""
        lines = "".join(json.dumps(record, ensure_ascii=False) + "\n" for record in records)
        self.guard.write_bytes(path, existing + lines.encode("utf-8"))

    def add_results(self, *, problem_id: str, title: str, folder: str, claims: list[Claim],
                    global_epoch: int) -> None:
        records = [
            {
                "uid": f"{problem_id}:{claim.id}",
                "problem": problem_id,
                "problem_title": title,
                "folder": folder,
                "claim": claim.id,
                "kind": claim.kind,
                "trust": claim.trust,
                "statement": claim.statement,
                "lean_decl": claim.lean_decl,
                "lean_file": claim.lean_file,
                "global_epoch": global_epoch,
                "time": utc_now(),
            }
            for claim in claims
        ]
        with self._lock:
            self._append(self.paths.knowledge_results, records)
            self._render()

    def add_relevance(self, *, source_problem: str, links: list[dict[str, Any]], known_problems: set[str],
                      global_epoch: int) -> list[dict[str, Any]]:
        """Record links to other known problems; returns the accepted links."""
        records = [
            {
                "from": source_problem,
                "to": link["problem_id"],
                "claims": list(link.get("claims", [])),
                "why": link.get("why", ""),
                "global_epoch": global_epoch,
                "time": utc_now(),
            }
            for link in links
            if link.get("problem_id") in known_problems and link.get("problem_id") != source_problem
        ]
        with self._lock:
            self._append(self.paths.knowledge_relevance, records)
        return records

    def results(self) -> list[dict[str, Any]]:
        with self._lock:
            return read_jsonl(self.paths.knowledge_results)

    def relevance_to(self, problem_id: str, *, after_global_epoch: int | None) -> list[dict[str, Any]]:
        with self._lock:
            links = read_jsonl(self.paths.knowledge_relevance)
        return [
            link for link in links
            if link.get("to") == problem_id
            and (after_global_epoch is None or int(link.get("global_epoch", 0)) > after_global_epoch)
        ]

    def _render(self) -> None:
        results = read_jsonl(self.paths.knowledge_results)
        order = {trust: index for index, trust in enumerate(TRUST_ORDER)}
        results.sort(key=lambda item: (order.get(item.get("trust"), 99), item.get("problem", ""), item.get("claim", "")))
        lines = [
            "# Accepted results across problems",
            "",
            "Generated by lean-orch. Trust levels: `lean_verified` (Lean kernel + faithful statement),",
            "`reproduced` (independent re-run + critic), `critic_accepted` (informal, reviewed).",
            "",
            "| Trust | Problem | Claim | Kind | Statement | Lean |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for item in results:
            statement = " ".join(str(item.get("statement", "")).split())
            if len(statement) > 220:
                statement = statement[:217] + "..."
            statement = statement.replace("|", "\\|")
            lean = f"`{item['lean_decl']}`" if item.get("lean_decl") and item.get("trust") == "lean_verified" else ""
            link = f"[{item.get('problem_title', item.get('problem'))}](../problems/{item.get('folder')}/PROGRESS.md)"
            lines.append(
                f"| {item.get('trust')} | {link} | {item.get('claim')} | {item.get('kind')} | {statement} | {lean} |"
            )
        self.guard.write_text(self.paths.knowledge_md, "\n".join(lines) + "\n")
